controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

payment:
    path: /payment
    controller: App\Controller\PaymentController::index
    methods: [GET, POST]
